Algoritmo "Operações Aritméticas"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Gremaud
// Data atual  : 11/10/2021
Var
// Seção de Declarações das variáveis 
   valor1, valor2, valor3, resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       valor1:=10
       valor2:=10
       valor3:=10
       resultado:=((valor1*valor2+valor2)/ valor3)
        escreval("Resultado:", resultado)

Fimalgoritmo